### PR TITLE
F replayview settlers

### PR DESCRIPTION
**Pull request by leRoe93**
Settlers Replay View is now initially implemented and works out fine (live as well). 

I followed exactly the same structure of the implementations for the CBRShooter to ensure a similar
structure which could later on even be abstracted into the upper inheritance base class. 

As the word "initially" already indicates, it is of course not fully completed, things missing are:

- Map image as well as other textures are not sent by Settlers yet (Map Image is just a simple screen shot to provide a better look for now)
- Updating the map consequently is not really implemented yet 

Other things to notice for the replay view: 

- Textures for cities and villages and even for the streets are VERY similar in the game and if you have a bird-view, you cannot really tell the difference, we need to agree on a solution for that
- As we need to place real game objects on the settlers game board we very likely will need a scaling method in the UIHelper that fits the textures to the map size accordingly for correct representation

Other things may come up until tomorrow when we meet :)

### CODE REVIEW

**Review by VocalTrance — COMMENTED** [review]
Great job!
Gonna look into the settlers map image for now.
Regarding the objects, we could just use different game objects inside settlers.
At worst, were breaking the way that it looks (overlapping of sorts), but game logic should not be impaired.

**Comment by VocalTrance** [comment]
Settlers of Catan dev has now sends the images and the replay view uses the map image.
Works great 👍 

Images of objects in Settlers not touched yet.

**Comment by leRoe93** [comment]
Nice thanks, looking forward seeing it tomorrow. 

I can think of another approach to distinguish between visuals in the replay view that are not very well distinguishible on the game side. 

As part of meta information of the game we could send an extra annotation parameter - a single letter would be enough. V for Village and T for town in this case. 

VISAB will handle these objects in a manner which places this letter with a simple label directly next to or even within the visual itself (depends on what is more convenient to see with human eyes 😅) 

Greeeetz

**Comment by leRoe93** [comment]
Latest changes add functionality to show the underlying map of the replay view in either colorised or black-and-white style. 

For example in settlers, things are way better visible if the map is coloured. 
However, the color-coding of the players may be hardly visible if the map is always coloured per default. 

Additional the `greyScaleImage` method of the `UiHelper` now has a parameter for providing a contrast, which may help if different maps need different contrasts to have a better visibility of the respective map contents on it. 

Note: not tested for Settlers, because I was doing this on my MacBook and I only have a Shooter file, but as the implementation is exactly the same it should work out - in the worst case we would need a very little bug fix.

**Comment by leRoe93** [comment]
Hey everyone, current state of this branch actually works quite well in general although there are some things not completely clean. 

First note: Have the Unity Games with current state of dev branch to be compatible.

Current state introduces: 

- Map Object usage as well for the shooter and settlers (thanks to @VocalTrance  and @Marshmellow24)
- Vector2 is now generic and I replaced in on any occasion with Double to be more accurate
- CBRShooters pathing is now fixed with the new Double vector because it is much more accurate
- Settlers replay view initializes all game objects based on the last data entry of the file, reason for that is that you need to set the children elements to the draw pane and if I do so for every iteration, I need to do very costly operations for the image views and the replay view runs into concurrent modification exceptions or simply the UI is very bad, because the update method takes too much time compared to the update loops time interval (e.g. turn slider jumps a few entries when velocity is put higher)


Small bugs / issues with the current state are:
- The tactic of using the last data entry is not compliant with the live view as of now, because the last data entry always changes in there. This could be solved with another publish-subscribe across the view and view model.
- The positioning of the elements is not completely correct, need to debug this with a deep-dive into the `CoordinateHelper` again
- Currently there is no real check within the map updating, that finds out if the city or the "pre-village" shall be visible

Any help on that is warmly welcome, but I will of course spend as much time as I can in the next two days before I will leave for vacation over the weekend.

**Pull request merged**
